import { ConvertLangMap, ContentRegxConfig } from "../constants/commonConfig";

export const StyleKeys = [
  "backgroundColor",
  "textColor",
  "fontSize",
  "margin",
  "letterSpacing",
  "paraSpacing",
  "scale",
  "brightness",
  "fontFamily",
  "subFontFamily",
  "lineHeight",
  "textAlign",
  "textOrientation",
  "convertChinese",
  "selectAction",
  "fullTranslationMode",
  "readerMode",
  "pdfReaderMode",
  "isBold",
  "isIndent",
  "isSliding",
  "isUnderline",
  "isShadow",
  "isItalic",
  "isInvert",
  "isBionic",
  "isHyphenation",
  "isOrphanWidow",
  "isKeepPDFBackground",
  "isAllowScript",
  "isStartFromEven",
  "isHideBackground",
  "isHideFooter",
  "isHideHeader",
  "isHideAIButton",
  "isHideScaleButton",
  "isHidePDFConvertButton",
  "isHidePageButton",
  "isHideMenuButton",
  "isHideAudiobookButton",
  "isShowPageBorder",
];

export const HighlightStyleTypes = [
  { value: "background", label: "Highlight background" },
  { value: "underline", label: "Underline" },
  { value: "strikethrough", label: "Strikethrough" },
  { value: "wavy", label: "Wavy underline" },
];

export const HighlightPresetColors: Record<string, string[]> = {
  background: ["#F3C9C9", "#FEF3CD", "#CEFACD", "#CDE9FA"],
  underline: ["#FF0000", "#60A5FA", "#FF9900", "#2EFF2E"],
  strikethrough: ["#FF0000", "#60A5FA", "#FF9900", "#2EFF2E"],
  wavy: ["#FF0000", "#60A5FA", "#FF9900", "#2EFF2E"],
};

export const PresetThemeList = [
  { key: "yellow", textColor: "rgba(89, 68, 41,1)", backgroundColor: "rgba(233, 216, 188,1)", title: "羊皮" },
  { key: "green", textColor: "rgba(54, 80, 62,1)", backgroundColor: "rgba(197, 231, 207,1)", title: "护眼" },
  { key: "light", textColor: "rgba(0,0,0,1)", backgroundColor: "rgba(255,255,255,1)", title: "白天" },
  { key: "night", textColor: "rgba(255,255,255,1)", backgroundColor: "rgba(44,47,49,1)", title: "黑夜" },
  { key: "sepia", textColor: "rgba(93, 64, 55,1)", backgroundColor: "rgba(245, 235, 220,1)", title: "古卷" },
  { key: "blue", textColor: "rgba(28, 52, 84,1)", backgroundColor: "rgba(230, 240, 250,1)", title: "晨雾" },
  { key: "purple", textColor: "rgba(68, 42, 84,1)", backgroundColor: "rgba(240, 230, 250,1)", title: "紫萝" },
  { key: "pink", textColor: "rgba(84, 42, 68,1)", backgroundColor: "rgba(250, 235, 245,1)", title: "樱花" },
  { key: "brown", textColor: "rgba(74, 54, 42,1)", backgroundColor: "rgba(240, 230, 215,1)", title: "木纹" },
  { key: "gray", textColor: "rgba(64, 64, 64,1)", backgroundColor: "rgba(240, 240, 240,1)", title: "素雅" },
  { key: "darkgreen", textColor: "rgba(200, 220, 200,1)", backgroundColor: "rgba(25, 35, 30,1)", title: "深林" },
  { key: "darkblue", textColor: "rgba(200, 210, 230,1)", backgroundColor: "rgba(20, 30, 45,1)", title: "深海" },
  { key: "coral", textColor: "rgba(84, 50, 42,1)", backgroundColor: "rgba(255, 235, 230,1)", title: "珊瑚" },
  { key: "mint", textColor: "rgba(42, 74, 64,1)", backgroundColor: "rgba(230, 250, 245,1)", title: "薄荷" },
  { key: "lavender", textColor: "rgba(54, 42, 74,1)", backgroundColor: "rgba(245, 240, 255,1)", title: "薰衣" },
  { key: "cream", textColor: "rgba(74, 64, 42,1)", backgroundColor: "rgba(255, 250, 240,1)", title: "奶油" },
  { key: "darkbrown", textColor: "rgba(230, 215, 200,1)", backgroundColor: "rgba(35, 25, 20,1)", title: "深棕" },
  { key: "olive", textColor: "rgba(64, 74, 42,1)", backgroundColor: "rgba(240, 245, 230,1)", title: "橄榄" },
  { key: "rose", textColor: "rgba(84, 42, 54,1)", backgroundColor: "rgba(255, 240, 245,1)", title: "玫瑰" },
  { key: "slate", textColor: "rgba(54, 64, 74,1)", backgroundColor: "rgba(235, 240, 245,1)", title: "石板" },
];

export const SpeechList = [
  { label: "English", code: "en", example: "To be, or not to be, that is the question." },
  { label: "Simplified Chinese", code: "zh", example: "千里之行，始于足下。" },
  { label: "Japanese", code: "ja", example: "猿も木から落ちる。" },
  { label: "Korean", code: "ko", example: "가는 날이 장날이다." },
  { label: "French", code: "fr", example: "Liberté, égalité, fraternité." },
  { label: "German", code: "de", example: "Der Weg ist das Ziel." },
  { label: "Spanish", code: "es", example: "La vida es un sueño." },
  { label: "Italian", code: "it", example: "Dolce far niente." },
  { label: "Russian", code: "ru", example: "Век живи, век учись." },
  { label: "Portuguese", code: "pt", example: "Saudade é um sentimento profundo." },
  { label: "Hindi", code: "hi", example: "सपने वो नहीं जो हम सोते वक्त देखते हैं।" },
  { label: "Afrikaans", code: "af", example: "Die lewe is 'n geskenk." },
  { label: "Amharic", code: "am", example: "ዕውቀት ብርሃን ነው።" },
  { label: "Arabic", code: "ar", example: "العلم نور والجهل ظلام." },
  { label: "Azerbaijani", code: "az", example: "Elm işıqdır, cəhalət zülmət." },
  { label: "Bulgarian", code: "bg", example: "Знанието е сила." },
  { label: "Bengali", code: "bn", example: "জ্ঞানই শক্তি।" },
  { label: "Bosnian", code: "bs", example: "Znanje je moć." },
  { label: "Catalan", code: "ca", example: "El saber no ocupa lloc." },
  { label: "Czech", code: "cs", example: "Bez práce nejsou koláče." },
  { label: "Welsh", code: "cy", example: "Nid aur popeth melyn." },
  { label: "Danish", code: "da", example: "Lykken er ikke et sted, men en retning." },
  { label: "Greek", code: "el", example: "Η γνώση είναι δύναμη." },
  { label: "Estonian", code: "et", example: "Teadmine on jõud." },
  { label: "Basque", code: "eu", example: "Jakitea boterea da." },
  { label: "Persian", code: "fa", example: "دانش قدرت است." },
  { label: "Finnish", code: "fi", example: "Tieto on valtaa." },
  { label: "Filipino", code: "fil", example: "Ang kaalaman ay kapangyarihan." },
  { label: "Irish", code: "ga", example: "Is fearr Gaeilge briste ná Béarla cliste." },
  { label: "Galician", code: "gl", example: "O saber non ocupa lugar." },
  { label: "Gujarati", code: "gu", example: "જ્ઞાન શક્તિ છે." },
  { label: "Hebrew", code: "he", example: "ידע הוא כוח." },
  { label: "Croatian", code: "hr", example: "Znanje je moć." },
  { label: "Hungarian", code: "hu", example: "A tudás hatalom." },
  { label: "Armenian", code: "hy", example: "Գիտելիքը ուժ է." },
  { label: "Indonesian", code: "id", example: "Pengetahuan adalah kekuatan." },
  { label: "Icelandic", code: "is", example: "Þekking er máttur." },
  { label: "Inuktitut", code: "iu", example: "ᐃᓕᓐᓂᐊᕐᓂᖅ ᐱᒻᒪᕆᐅᕗᖅ." },
  { label: "Javanese", code: "jv", example: "Ilmu iku kelakone kanthi laku." },
  { label: "Georgian", code: "ka", example: "ცოდნა ძალაა." },
  { label: "Kazakh", code: "kk", example: "Білім — күш." },
  { label: "Khmer", code: "km", example: "ចំណេះដឹងគឺជាអំណាច។" },
  { label: "Kannada", code: "kn", example: "ಜ್ಞಾನವೇ ಶಕ್ತಿ." },
  { label: "Lao", code: "lo", example: "ຄວາມຮູ້ຄືພະລັງ." },
  { label: "Lithuanian", code: "lt", example: "Žinios yra jėga." },
  { label: "Latvian", code: "lv", example: "Zināšanas ir spēks." },
  { label: "Macedonian", code: "mk", example: "Знаењето е моќ." },
  { label: "Malayalam", code: "ml", example: "അറിവ് ശക്തിയാണ്." },
  { label: "Mongolian", code: "mn", example: "Мэдлэг бол хүч." },
  { label: "Marathi", code: "mr", example: "ज्ञान हीच शक्ती आहे." },
  { label: "Malay", code: "ms", example: "Ilmu itu cahaya." },
  { label: "Maltese", code: "mt", example: "L-għarfien huwa l-poter." },
  { label: "Burmese", code: "my", example: "ဗဟုသုတသည် အားဖြစ်သည်။" },
  { label: "Norwegian", code: "nb", example: "Kunnskap er makt." },
  { label: "Nepali", code: "ne", example: "ज्ञान नै शक्ति हो।" },
  { label: "Dutch", code: "nl", example: "Kennis is macht." },
  { label: "Odia", code: "or", example: "ଜ୍ଞାନ ହିଁ ଶକ୍ତି।" },
  { label: "Punjabi", code: "pa", example: "ਗਿਆਨ ਹੀ ਸ਼ਕਤੀ ਹੈ।" },
  { label: "Polish", code: "pl", example: "Wiedza to potęga." },
  { label: "Pashto", code: "ps", example: "د پوهې ډیوه روښانه ده." },
  { label: "Romanian", code: "ro", example: "Cartea este o comoară." },
  { label: "Sinhala", code: "si", example: "දැනුම බලයකි." },
  { label: "Slovak", code: "sk", example: "Vedomosti sú sila." },
  { label: "Slovenian", code: "sl", example: "Znanje je moć." },
  { label: "Somali", code: "so", example: "Aqoontu waa iftiin." },
  { label: "Albanian", code: "sq", example: "Dija është fuqi." },
  { label: "Serbian", code: "sr", example: "Знање је моћ." },
  { label: "Sundanese", code: "su", example: "Élmu éta cahaya." },
  { label: "Swedish", code: "sv", example: "Kunskap är makt." },
  { label: "Swahili", code: "sw", example: "Maarifa ni nguvu." },
  { label: "Tamil", code: "ta", example: "அறிவே ஆற்றல்." },
  { label: "Telugu", code: "te", example: "జ్ఞానమే శక్తి." },
  { label: "Thai", code: "th", example: "ความรู้คือพลัง." },
  { label: "Turkish", code: "tr", example: "Bilgi güçtür." },
  { label: "Ukrainian", code: "uk", example: "Знання — сила." },
  { label: "Urdu", code: "ur", example: "علم ہی طاقت ہے۔" },
  { label: "Uzbek", code: "uz", example: "Bilim – kuch." },
  { label: "Vietnamese", code: "vi", example: "Học vấn là sức mạnh." },
  { label: "Wu Chinese", code: "wuu", example: "学问是力量。" },
  { label: "Cantonese", code: "yue", example: "知識就係力量。" },
  { label: "Zulu", code: "zu", example: "Ulwazi lungamandla." },
];

export const KookitConfig = {
  ConvertLangMap,
  ContentRegxConfig,
  StyleKeys,
  HighlightStyleTypes,
  HighlightPresetColors,
  PresetThemeList,
  SpeechList,
};

