export const ConvertLangMap: Record<string, string> = {
  en: "English",
  zhCN: "Chinese",
  zhTW: "Chinese",
  zhMO: "Chinese",
  tr: "Turkish",
  ar: "Arabic",
  ro: "Romanian",
  pl: "Polish",
  cs: "Czech",
  ja: "Japanese",
  ta: "Tamil",
  uk: "Ukrainian",
  sl: "Slovenian",
  bo: "Tibetan",
  id: "Indonesian",
  hy: "Armenian",
  el: "Greek",
  hu: "Hungarian",
  hi: "Hindi",
  bg: "Bulgarian",
  nl: "Dutch",
  it: "Italian",
  bn: "Bengali",
  tl: "Tagalog",
  sv: "Swedish",
  ga: "Irish",
  ko: "Korean",
  de: "German",
  ru: "Russian",
  es: "Spanish",
  fr: "French",
  fa: "Persian",
  ptBR: "Portuguese",
  th: "Thai",
  sr: "Serbian",
  am: "Amharic",
  da: "Danish",
  fi: "Finnish",
  ie: "Interlingue",
  pt: "Portuguese",
  vi: "Vietnamese",
};

export const ContentRegxConfig = [
  {
    label: "Default parser",
    value: "Default parser",
    subtitle: "Suitable for most txt files",
    regex: "",
  },
  {
    label: "Chinese novel parser",
    value: "Chinese novel parser",
    subtitle: "Suitable for most Chinese novels, eg. 第一章，第2回",
    regex:
      "^\\s*(第[0-9一二三四五六七八九十百千万零壹贰叁肆陆柒捌玖拾佰仟]+[章回])\\s*",
  },
  {
    label: "English novel parser",
    value: "English novel parser",
    subtitle: "Suitable for most English novels, eg. Chapter 1, Part II",
    regex: "^\\s*(Chapter|Part|Book|CHAPTER|PART|BOOK)\\s*",
  },
  {
    label: "Number parser",
    value: "Number parser",
    subtitle: "Suitable for novels with number chapter titles, eg. 1, 2, 3",
    regex:
      "^\\s*([0-9]+[\\s.、：:·\\-—]+|[一二三四五六七八九十百千万零]+[\\s.、：:·\\-—]+).+",
  },
];
